config/routes.rb
Shewbot::Application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :questions

  get "rake/routes"

  root to: 'static_pages#home'

  match '/login', to: 'static_pages#login'

  match '/auth/twitter/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/sessions/visitor_count', to: 'sessions#visitor_count'

  match '/titles/create', to: 'titles#create'
  match '/titles', to: 'titles#index'
  match '/title/:id/upvote', to: 'titles#upvote'

  match '/links/create', to: 'links#create'
  match '/links', to: 'links#index'

  match '/questions/create', to: 'questions#create'
  match '/questions', to: 'questions#index'

  match '/shows/current', to: 'shows#current', via: :get, :defaults => { :format => 'json' }

  resources :irc_users, only: :show

  resources :shows, only: [:index, :show]

  namespace :admin do
    resources :apis
    resources :users
    resources :votes
    resources :titles
    resources :shows
    resources :irc_users
    resources :visitors, only: [:index]
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :title_id, :voterip

  validates_uniqueness_of :voterip, :scope => :title_id

  validates :title_id, :presence => true

  belongs_to :title, :counter_cache => true
end

app/controllers/admin/votes_controller.rb
class Admin::VotesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  def edit
    @vote = Vote.find(params[:id])
  end

  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to admin_vote_url(@vote), notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to admin_vote_url(@vote), notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to admin_votes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/votes_controller.rb
class Admin::VotesController < ApplicationController

  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end


  def edit
    @vote = Vote.find(params[:id])
  end

  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to admin_vote_url(@vote), notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to admin_vote_url(@vote), notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to admin_votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admin/votes/_form.html.erb
<%= form_for [:admin, @vote] do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voterip %><br />
    <%= f.text_field :voterip %>
  </div>
  <div class="field">
    <%= f.label :title_id %><br />
    <%= f.number_field :title_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Vote', admin_vote_path(@vote) %> |
<%= link_to 'Back', admin_votes_path %>

app/views/admin/votes/index.html.erb
<h1>Listing votes</h1>

<table class="table">
  <tr>
    <th>Voterip</th>
    <th>Title</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.voterip %></td>
    <td><%= link_to vote.title.title, admin_title_path(vote.title) %></td>
    <td><%= vote.created_at %></td>
    <td><%= vote.updated_at %></td>
    <td><%= link_to 'Show', admin_vote_path(vote) %></td>
    <td><%= link_to 'Edit', edit_admin_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', admin_vote_path(vote), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_admin_vote_path %>

app/views/admin/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_votes_path %>

app/views/admin/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Voterip:</b>
  <%= @vote.voterip %>
</p>

<p>
  <b>Title:</b>
  <%= link_to @vote.title.title, admin_title_path(@vote.title) %>
</p>

<p>
  <b>Created:</b>
  <%= @vote.created_at %>
</p>

<p>
  <b>Updated:</b>
  <%= @vote.updated_at %>
</p>


<%= link_to 'Edit', edit_admin_vote_path(@vote) %> |
<%= link_to 'Back', admin_votes_path %>