config/routes.rb
Shewbot::Application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :questions

  get "rake/routes"

  root to: 'static_pages#home'

  match '/login', to: 'static_pages#login'

  match '/auth/twitter/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/sessions/visitor_count', to: 'sessions#visitor_count'

  match '/titles/create', to: 'titles#create'
  match '/titles', to: 'titles#index'
  match '/title/:id/upvote', to: 'titles#upvote'

  match '/links/create', to: 'links#create'
  match '/links', to: 'links#index'

  match '/questions/create', to: 'questions#create'
  match '/questions', to: 'questions#index'

  match '/shows/current', to: 'shows#current', via: :get, :defaults => { :format => 'json' }

  resources :irc_users, only: :show

  resources :shows, only: [:index, :show]

  namespace :admin do
    resources :apis
    resources :users
    resources :votes
    resources :titles
    resources :shows
    resources :irc_users
    resources :visitors, only: [:index]
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  attr_accessible :title, :episode_number, :art

  validates :title, presence: true

  has_many :titles, :dependent => :destroy
  has_many :links, :dependent => :destroy
  has_many :questions, :dependent => :destroy

  def self.current_show
  	self.order("created_at DESC").first
  end

  def self.update_current_show(show_data = [])
    title = show_data[0]
    art = show_data[1]

    current_show = self.order("created_at DESC").first

    if !title.nil? && Settings.live_url.nil?
      return current_show
    end

    if current_show.nil? || current_show.title != title || current_show.created_at < 4.hours.ago
    	self.transaction do 
    		current_show = self.order("created_at DESC").lock(true).first

    		if current_show.nil? || current_show.title != title || current_show.created_at < 4.hours.ago
    			current_show = self.create(title: title, art: art)
    		end
    	end
    end

  	return current_show
  end
end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < ApplicationController
  before_filter :authenticate_user!

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to admin_show_url(@show), notice: 'Show was successfully created.' }
        format.json { render json: @show, status: :created, location: admin_show_url(@show) }
      else
        format.html { render action: "new" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to admin_show_url(@show), notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to admin_shows_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def current
    @show = Show.current_show

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @show }
    end
  end

  def index
    @shows = Show.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  def show
    @show = Show.find(params[:id])
    @titles = @show.titles.order("votes_count DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/admin/shows/_form.html.erb
<%= form_for [:admin, @show] do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Show name" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :episode_number %><br />
    <%= f.text_field :episode_number %>
  </div>
  <div class="field">
    <%= f.label :art %><br />
    <%= f.text_field :art %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_show_path(@show) %> |
<%= link_to 'Back', admin_shows_path %>

app/views/admin/shows/index.html.erb
<h1>Listing episodes</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Episode Number</th>
    <th>Art</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shows.each do |show| %>
  <tr>
    <td><%= show.title %></td>
    <td><%= show.episode_number %></td>
    <td><%= image_tag(show.art, :width => 50, :height => 50) if !show.art.nil? %></td>
    <td><%= show.created_at %></td>
    <td><%= show.updated_at %></td>
    <td><%= link_to 'View Show', show_path(show) %></td>
    <td><%= link_to 'Edit', edit_admin_show_path(show) %></td>
    <td><%= link_to 'Destroy', admin_show_path(show), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Show', new_admin_show_path %>

app/views/admin/shows/new.html.erb
<h1>Create a new episode</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_shows_path %>

app/views/admin/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @show.title %>
</p>

<p>
  <b>Episode Number:</b>
  <%= @show.episode_number %>
</p>

<p>
  <b>Created at:</b>
  <%= @show.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @show.updated_at %>
</p>


<%= link_to 'Edit', edit_admin_show_path(@show) %> |
<%= link_to 'Back', admin_shows_path %>