config/routes.rb
Shewbot::Application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :questions

  get "rake/routes"

  root to: 'static_pages#home'

  match '/login', to: 'static_pages#login'

  match '/auth/twitter/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/sessions/visitor_count', to: 'sessions#visitor_count'

  match '/titles/create', to: 'titles#create'
  match '/titles', to: 'titles#index'
  match '/title/:id/upvote', to: 'titles#upvote'

  match '/links/create', to: 'links#create'
  match '/links', to: 'links#index'

  match '/questions/create', to: 'questions#create'
  match '/questions', to: 'questions#index'

  match '/shows/current', to: 'shows#current', via: :get, :defaults => { :format => 'json' }

  resources :irc_users, only: :show

  resources :shows, only: [:index, :show]

  namespace :admin do
    resources :apis
    resources :users
    resources :votes
    resources :titles
    resources :shows
    resources :irc_users
    resources :visitors, only: [:index]
  end

end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :created_at, :irc_user_id, :show_id, :title

  validates :title, :presence => true, :length => { :maximum => 50 }
  validates :irc_user_id, :presence => true
  validates :show_id, :presence => true
  validates :title_lc, :presence => true

  validates_uniqueness_of :title_lc, :scope => :show_id, :message => 'Title already submitted'

  belongs_to :show, :counter_cache => true
  belongs_to :irc_user

  has_many :votes, :dependent => :destroy

  after_initialize :set_title_lc

  scope :with_votes_from_ip, lambda { |ipaddress| joins("LEFT OUTER JOIN votes ON titles.id = votes.title_id AND votes.voterip = '#{ipaddress}'").select("titles.*, votes.id AS voteid") }
  scope :with_irc_users_and_votes, lambda { |ipaddress| joins("LEFT OUTER JOIN votes ON titles.id = votes.title_id AND votes.voterip = '#{ipaddress}' LEFT OUTER JOIN irc_users ON titles.irc_user_id = irc_users.id").select("titles.*, irc_users.name AS irc_user_name, votes.id AS voteid") }

  def set_title_lc
  	if self.title
	  	self.title_lc = self.title.downcase
	  end
  end

end

app/controllers/admin/titles_controller.rb
class Admin::TitlesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @titles = Title.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @titles.as_json(:include => :irc_user) }
    end
  end

  def show
    @title = Title.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @title }
    end
  end

  def new
    @title = Title.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @title }
    end
  end

  def edit
    @title = Title.find(params[:id])
  end

  def create
    @title = Title.new(params[:title])

    respond_to do |format|
      if @title.save
        format.html { redirect_to admin_title_url(@title), notice: 'Title was successfully created.' }
        format.json { render json: @title, status: :created, location: @title }
      else
        format.html { render action: "new" }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @title = Title.find(params[:id])

    respond_to do |format|
      if @title.update_attributes(params[:title])
        format.html { redirect_to admin_title_url(@title), notice: 'Title was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @title = Title.find(params[:id])
    @title.destroy

    respond_to do |format|
      format.html { redirect_to admin_titles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  include TitlesHelper

	before_filter :check_api_key, only: [:create]
	respond_to :json

  def index
    @titles = Show.current_show.titles.with_irc_users_and_votes(request.remote_ip)

    Cache.visit(request.remote_ip)

    render json: @titles.as_json
  end

  def upvote
		title = Title.find(params[:id])

		if title
			vote = title.votes.new(voterip: request.remote_ip)

			if title.show.id == Show.maximum('id') && vote.save
				render json: vote, status: :created
			else
				render json: vote.errors, status: :unprocessable_entity
			end
		end
  end

  def create
    title = Show.update_current_show(fetch_live_show).titles.new(title: params[:title])

  	title.irc_user = IrcUser.find_or_create_by_name(params[:user])

    what_is_live = fetch_live_show

    if title.show_id.nil?
      render json: { 'Show' => [ 'is not live' ], 'live' => what_is_live }, status: :unprocessable_entity
    elsif title.save
      render json: title, status: :created
    else
      render json: { 'errors' => title.errors }, status: :unprocessable_entity
    end
  end

end

app/helpers/titles_helper.rb
module TitlesHelper
	require 'rest-client'

  def fetch_live_show_title
    title = nil

    if !Settings.live_url.nil?
      begin
        live_hash = JSON.parse(RestClient.get Settings.live_url)
        if live_hash and live_hash.has_key?("live") and live_hash["live"]
          broadcast = live_hash["broadcast"] if live_hash.has_key? "broadcast"
          title = broadcast["slug"] if broadcast.has_key? "slug"
          title = broadcast["title"] if broadcast.has_key? "title"
        end
      rescue
        puts "Error: #{Settings.live_url} looks to be down."
      end
    end

    return title
  end

  def fetch_live_show
    show_data = nil

    if !Settings.live_url.nil?
      begin
        live_hash = JSON.parse(RestClient.get Settings.live_url)
        if live_hash and live_hash.has_key?("live") and live_hash["live"]
          broadcast = live_hash["broadcast"] if live_hash.has_key? "broadcast"
          title = broadcast["slug"] if broadcast.has_key? "slug"
          title = broadcast["title"] if broadcast.has_key? "title"
          art = broadcast["show_art"] if broadcast.has_key? "show_art"
          show_data = {art: art, title: title}
        end
      rescue  Exception => e 
        puts "Error: #{Settings.live_url} looks to be down. #{e.message}"
      end
    end

    return show_data[:title], show_data[:art]
  end

end

app/views/admin/titles/_form.html.erb
<%= form_for [:admin, @title] do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :irc_user_id %><br />
    <%= f.number_field :irc_user_id %>
  </div>
  <div class="field">
    <%= f.label :show_id %><br />
    <%= f.number_field :show_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/titles/edit.html.erb
<h1>Editing title</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_title_path(@title) %> |
<%= link_to 'Back', admin_titles_path %>

app/views/admin/titles/index.html.erb
<h1>Listing titles</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Title lc</th>
    <th>Ircuser</th>
    <th>Show</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @titles.each do |title| %>
  <tr>
    <td><%= title.title %></td>
    <td><%= title.title_lc %></td>
    <td><%= title.irc_user.name %></td>
    <td><%= title.show.title %></td>
    <td><%= title.created_at %></td>
    <td><%= title.updated_at %></td>
    <td><%= link_to 'Show', admin_title_path(title) %></td>
    <td><%= link_to 'Edit', edit_admin_title_path(title) %></td>
    <td><%= link_to 'Destroy', admin_title_path(title), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Title', new_admin_title_path %>

app/views/admin/titles/new.html.erb
<h1>New title</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_titles_path %>

app/views/admin/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @title.title %>
</p>

<p>
  <b>Title lc:</b>
  <%= @title.title_lc %>
</p>

<p>
  <b>Created at:</b>
  <%= @title.created_at %>
</p>

<p>
  <b>Ircuser:</b>
  <%= @title.irc_user_id %>
</p>


<%= link_to 'Edit', edit_admin_title_path(@title) %> |
<%= link_to 'Back', admin_titles_path %>