config/routes.rb
Shewbot::Application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :questions

  get "rake/routes"

  root to: 'static_pages#home'

  match '/login', to: 'static_pages#login'

  match '/auth/twitter/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/sessions/visitor_count', to: 'sessions#visitor_count'

  match '/titles/create', to: 'titles#create'
  match '/titles', to: 'titles#index'
  match '/title/:id/upvote', to: 'titles#upvote'

  match '/links/create', to: 'links#create'
  match '/links', to: 'links#index'

  match '/questions/create', to: 'questions#create'
  match '/questions', to: 'questions#index'

  match '/shows/current', to: 'shows#current', via: :get, :defaults => { :format => 'json' }

  resources :irc_users, only: :show

  resources :shows, only: [:index, :show]

  namespace :admin do
    resources :apis
    resources :users
    resources :votes
    resources :titles
    resources :shows
    resources :irc_users
    resources :visitors, only: [:index]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :admin

  validates :name, :presence => true

  validates_inclusion_of :admin, :in => [true, false]

  has_many :authorizations

  after_initialize :set_defaults

  def set_defaults
  	self.admin ||= false
  end

  before_create :create_remember_token

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

  def admin?
    self.admin
  end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    params[:user].except! :password if params[:user][:password].blank?

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if !@user.id.nil? %>
    <p>Updating your own password will log you out and require you to log in with the new password.</p>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :admin %> <%= f.label :admin %><br />
    </label>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Admin</th>
    <th>Created</th>
    <th>Updated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.admin %></td>
    <td><%= user.created_at %></td>
    <td><%= user.updated_at %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin %>
</p>

<p>
  <b>Created:</b>
  <%= @user.created_at %>
</p>

<p>
  <b>Updated:</b>
  <%= @user.updated_at %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>